# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
if [ "$TERM" = "linux" ]; then
	ZSH_THEME="dracula/dracula"
else
	ZSH_THEME="powerlevel10k/powerlevel10k"
fi

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

if [ "$TERM" = "linux" ]; then
	plugins=(git zsh-completions zsh-syntax-highlighting sudo forgit warhol)
else
	plugins=(git zsh-completions zsh-syntax-highlighting sudo zsh-autosuggestions forgit warhol)
fi

source $ZSH/oh-my-zsh.sh

# User configuration

if [[ -s '/etc/zsh_command_not_found' ]]; then
  source '/etc/zsh_command_not_found'
fi

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
#POWERLEVEL9K_DISABLE_RPROMPT=true
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\uE0B3'
#POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_CONTEXT_TEMPLATE="%n@%m"


POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_SHORTEN_DELIMITER=""                                                                                                                                                             
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='141'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='236'
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='141'
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='236'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND='141'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND='236'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='061'
POWERLEVEL9K_DIR_HOME_BACKGROUND='061'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='061'
POWERLEVEL9K_DIR_ETC_BACKGROUND='061'
POWERLEVEL9K_DIR_ROOT_BACKGROUND='061'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='253'
POWERLEVEL9K_DIR_HOME_FOREGROUND='253'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='253'
POWERLEVEL9K_DIR_ETC_FOREGROUND='253'
POWERLEVEL9K_DIR_ROOT_FOREROUND='253'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

setopt autocd correct
alias ls='colorls -l'
alias df="dfc -nW"
#alias diff="kitty +kitten diff"
alias sshk="kitty +kitten ssh"
alias cat="batcat"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

autoload -U compinit && compinit

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'
