- name: Install Polybar
  package:
    name: polybar
  become: true

- name: Create Polybar Directory
  file:
    path: "{{ polybar_config_dir }}/scripts"
    state: directory
    recurse: yes

- name: Copy configuration
  template:
    src: config.j2
    dest: "{{ polybar_config_dir }}/config"

- name: Install all scripts
  copy:
    src: scripts/
    dest: "{{ polybar_config_dir }}/scripts"
    mode: 0755
