- name: Copy Regolith Repo GPG key
  get_url:
    url: https://regolith-linux.github.io/package-repo/regolith.key
    dest: /etc/apt/trusted.gpg.d/regolith.asc
  become: true

- name: Add Regolith repo
  apt_repository:
    repo: deb [arch=amd64] https://regolith-release-ubuntu-jammy-amd64.s3.amazonaws.com jammy main
    state: present
  become: true

- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes
  become: true

- name: Install Regolith
  package:
    name: regolith-desktop
    state: present
  become: true

- name: Install lightDM
  package: 
    name: regolith-lightdm-config
    state: present
  become: true

- name: Delete Unneeded packages
  package: 
    name: gdm3 gnome-shell
    state: absent
  become: true

- name: Create Regolith config directory
  file:
    path: "{{ config_dir }}/i3"
    state: directory
    recurse: yes

- name: Configure i3
  copy:
    src: i3
    dest: "{{ config_dir }}/i3"

- name: Configure Xressources
  template:
    src: Xresources.j2
    dest: "{{ config_dir }}/Xresources"

- name: Create local bin directory
  file:
    path: "{{ local_bin_dir }}"
    state: directory
    recurse: yes

- name: Install Awesome-auto-layout
  get_url:
    url: https://gitlab.com/s3lect/awesome-i3-auto-layout/-/raw/master/awesome-auto-layout
    dest: "{{ local_bin_dir }}"
    mode: 0755

- name: Copy powermenu
  copy:
    src: powermenu.sh
    dest: "{{ config_dir }}/powermenu.sh"
    mode: 0755

- name: Disable
